name: Lint

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
